name: application demo workflow

on:
 push:
   branches:
   - main
   - feature/**

 # pull_request:
 #   branches:
 #   - main

jobs:
  demo: 
    name: Demo job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v6.1.0
      with:
        node-version: 16.x

    - name: Install Dep & Build
      run: |
         npm install
         npm run build   

    - name: Download a Build Artifact 
      uses: actions/download-artifact@v7.0.0
      with:
        name: ${{ github.run_id }}
        path: build

   
    # - name: setup nodejs
    #   run: |
    #      curl -s https://deb.nodesource.com/setup_16.x | sudo bash
    #      sudo apt install nodejs -y
    # - name: Install Dependencies
    #   run: npm install

    # - name: Build
    #   run: npm run build     
      
    - name: Gretting 
      run: echo "hello word"

    - name: list file
      run: ls -l

    - name: read file
      run: cat package.json
